# Generated by Django 5.2.4 on 2025-08-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acodes',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='appcomb',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='appprod',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='bcodes',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='combext',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='combtb',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='comppro',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='grouptb',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='kmeal',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='kpro',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='krev',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='kwkvat',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='miscsec',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='optpro',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='pchoice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='pditem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='pdvattb',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='prodext',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='shopstb',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
        migrations.AddField(
            model_name='stitems',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
    ]
