# Generated by Django 5.2.4 on 2025-09-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0002_acodes_last_updated_appcomb_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EposCombFreeProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMBONUMB', models.IntegerField(help_text='Combination product code.')),
                ('ITEM_DESC', models.CharField(help_text='Description of combination product.', max_length=20)),
                ('FREE_CHOICE_1', models.CharField(help_text='First free choice item.', max_length=40)),
                ('FREE_CHOICE_2', models.CharField(help_text='Second free choice item.', max_length=40)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
        migrations.CreateModel(
            name='EposFreeProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODNUMB', models.IntegerField(help_text='Product code.')),
                ('PRODNAME', models.CharField(help_text='Product name.', max_length=16)),
                ('FREE_CHOICE_1', models.CharField(help_text='First free choice item.', max_length=40)),
                ('FREE_CHOICE_2', models.CharField(help_text='Second free choice item.', max_length=40)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
        migrations.CreateModel(
            name='EposGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EPOS_GROUP_ID', models.IntegerField(help_text='ePOS group number.')),
                ('EPOS_GROUP_TITLE', models.CharField(help_text='ePOS group title.', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
        migrations.CreateModel(
            name='EposProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODNUMB', models.IntegerField(help_text='Product code.')),
                ('PRODNAME', models.CharField(help_text='Product name.', max_length=16)),
                ('ITEM_DESC', models.CharField(help_text='Description of item.', max_length=20)),
                ('EPOS_GROUP', models.IntegerField(help_text='ePOS group number.')),
                ('EPOS_SEQUENCE', models.IntegerField(help_text='ePOS sequence number.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODNUMB', models.IntegerField(help_text='Product code.')),
                ('PRODNAME', models.CharField(help_text='Product name.', max_length=16)),
                ('ITEM_DESC', models.CharField(help_text='Description of extra item.', max_length=20)),
                ('SQE_ORDER', models.IntegerField(help_text='ePOS sequence number.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
    ]
