# Generated by Django 5.2.4 on 2025-09-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0003_eposcombfreeprod_eposfreeprod_eposgroup_eposprod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='SQE_ORDER',
            new_name='SEQ_ORDER',
        ),
    ]
