# Generated by Django 5.2.4 on 2025-09-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0004_rename_sqe_order_extras_seq_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EposComb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMBONUMB', models.IntegerField(help_text='Combination product code.')),
                ('DESC', models.CharField(help_text='Name of combination product.', max_length=16)),
                ('ITEM_DESC', models.CharField(help_text='Description of combination product.', max_length=20)),
                ('EPOS_GROUP', models.IntegerField(help_text='ePOS group number.')),
                ('EPOS_SEQUENCE', models.IntegerField(help_text='ePOS sequence number.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
    ]
