# Generated by Django 5.2.4 on 2025-09-09 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0005_eposcomb'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmeal',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Statistics date (business day)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpro',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Statistics date (business day)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='krev',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Statistics date (business day)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='kmeal',
            unique_together={('stat_date', 'PRODNUMB')},
        ),
        migrations.AlterUniqueTogether(
            name='kpro',
            unique_together={('stat_date', 'PRODNUMB', 'COMBO')},
        ),
        migrations.AlterUniqueTogether(
            name='krev',
            unique_together={('stat_date',)},
        ),
    ]
