# Generated by Django 5.2.4 on 2025-09-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0006_kmeal_stat_date_kpro_stat_date_krev_stat_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extras',
        ),
    ]
