# Generated by Django 5.2.4 on 2025-09-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0007_delete_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingDel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACODE', models.IntegerField(help_text='Topping code.')),
                ('DESC', models.CharField(help_text='Description of topping.', max_length=20)),
                ('MENU_DESC', models.CharField(help_text='Menu description of topping.', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
    ]
