# Generated by Django 5.2.4 on 2025-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0008_toppingdel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EposAddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODNUMB', models.IntegerField(help_text='Product code.')),
                ('ADD_ONS', models.CharField(help_text='Comma-separated list of add-on product codes.', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
    ]
