# Generated by Django 5.2.4 on 2025-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0009_eposaddons'),
    ]

    operations = [
        migrations.AddField(
            model_name='eposaddons',
            name='PRODNAME',
            field=models.CharField(default='apple', help_text='Product name.', max_length=16),
            preserve_default=False,
        ),
    ]
