# Generated by Django 5.2.4 on 2025-11-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0010_eposaddons_prodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='eposprod',
            name='COLOUR_BLUE',
            field=models.IntegerField(default=255, help_text='Blue component of colour (0-255).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eposprod',
            name='COLOUR_GREEN',
            field=models.IntegerField(default=255, help_text='Green component of colour (0-255).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eposprod',
            name='COLOUR_RED',
            field=models.IntegerField(default=255, help_text='Red component of colour (0-255).'),
            preserve_default=False,
        ),
    ]
