# Generated by Django 5.2.4 on 2025-11-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0011_eposprod_colour_blue_eposprod_colour_green_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCODEALPH', models.CharField(help_text='First part of stock item code (letter).', max_length=1)),
                ('ST_CODENUM', models.IntegerField(help_text='Second part of stock item code (4-digit number).')),
                ('ITEM', models.CharField(help_text='Description for this stock item.', max_length=18)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBands',
            fields=[
                ('REC_ID', models.AutoField(help_text='ID of this record.', primary_key=True, serialize=False)),
                ('PRICE_ID', models.IntegerField(help_text='Price band.')),
                ('PRICE_SUB_ID', models.IntegerField(help_text='Sub ID for company under price band.')),
                ('SEQ_ORDER', models.IntegerField(help_text='Order for cycling through companies.')),
                ('SUPPLIER_CODE', models.CharField(help_text='Abbreviation of the name of this company.', max_length=4)),
                ('SUPPLIER_NAME', models.CharField(help_text='Name of this company.', max_length=25)),
                ('APPLY_HERE', models.BooleanField(help_text='True if this company is applicable to this shop.')),
                ('PARENT_ID', models.IntegerField(help_text='ID of its parent company.')),
                ('ACC_FIRM_NUM', models.IntegerField(help_text='ID in On_Acc table if on account company, else 0.')),
                ('ACCEPT_CASH', models.BooleanField(help_text='True if this company accepts cash payment.')),
                ('ACCEPT_CARD', models.BooleanField(help_text='True if this company accepts card payment.')),
                ('ACCEPT_ON_ACC', models.BooleanField(help_text='True if this company accepts on account payment.')),
                ('HOT_DRINK', models.BooleanField(help_text='True if hot drinks can be ordered via this company.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
            ],
        ),
    ]
