# Generated by Django 5.2.4 on 2025-11-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0012_estock_pricebands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceBands',
            new_name='PriceBand',
        ),
    ]
