# Generated by Django 5.2.4 on 2025-11-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0013_rename_pricebands_priceband'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceband',
            name='ACCEPT_COOKED_WASTE',
            field=models.BooleanField(default=0, help_text='True if this company accepts cooked waste payment.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceband',
            name='ACCEPT_CREW_FOOD',
            field=models.BooleanField(default=0, help_text='True if this company accepts crew food.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceband',
            name='ACCEPT_VOUCHER',
            field=models.BooleanField(default=0, help_text='True if this company accepts voucher payment.'),
            preserve_default=False,
        ),
    ]
