# Generated by Django 5.2.4 on 2025-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0014_priceband_accept_cooked_waste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstb',
            name='OPERATORS',
            field=models.CharField(default='T', help_text='Names of shop operators.', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopstb',
            name='TELEPHONE',
            field=models.CharField(default='9', help_text='Shop telephone number.', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopstb',
            name='VAT_NUMB',
            field=models.CharField(default='a', help_text='VAT number of shop.', max_length=12),
            preserve_default=False,
        ),
    ]
