# Generated by Django 5.2.4 on 2025-11-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0015_shopstb_operators_shopstb_telephone_shopstb_vat_numb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estock',
            old_name='SCODEALPH',
            new_name='CODEALPH',
        ),
        migrations.RenameField(
            model_name='priceband',
            old_name='ACCEPT_ON_ACC',
            new_name='ACCEPT_ONACC',
        ),
    ]
