# Generated by Django 5.2.4 on 2025-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_till', '0016_rename_scodealph_estock_codealph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceband',
            name='DELIV_SUPPLIER',
            field=models.BooleanField(default=0, help_text='True if this company delivers orders.'),
            preserve_default=False,
        ),
    ]
