"""
Django settings for epos project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dotenv
import ast

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
"""Base directory of the project (repository root)."""

# Explicitly load .env from project root. Use override=True so environment variables
# in the running process (e.g. set by hosting platform) can still supersede if desired.
dotenv.load_dotenv(BASE_DIR / '.env', override=True)

def env_bool(name: str, default: bool = False) -> bool:
    """Parse a boolean environment variable in a tolerant way.

    Accepts truthy: 1, true, yes, on (case-insensitive). Everything else is False.
    """
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {'1','true','yes','on'}

def env_list(name: str, default=None):
    """Parse a list environment variable.

    Supports either a comma-separated string (a,b,c) or a Python list literal (['a','b']).
    Returns list[str].
    """
    raw = os.getenv(name)
    if raw is None or raw.strip() == '':
        return default if default is not None else []
    txt = raw.strip()
    if txt.startswith('[') and txt.endswith(']'):
        try:
            parsed = ast.literal_eval(txt)
            if isinstance(parsed, (list, tuple)):
                return [str(x).strip() for x in parsed if str(x).strip()]
        except Exception:
            # fall back to comma parsing
            pass
    return [p.strip() for p in txt.split(',') if p.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') or 'INSECURE-CHANGE-ME'
    

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

raw_hosts_default = ['127.0.0.1','localhost']
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', default=raw_hosts_default)
if DEBUG:
    # During local development or explicit DEBUG, allow all hosts
    ALLOWED_HOSTS = ['*']

# CSRF trusted origins (update with your deployed domain)
CSRF_TRUSTED_ORIGINS = [
    'https://unclesams.pythonanywhere.com',
    'https://www.unclesams.pythonanywhere.com'
]


# Application definition

INSTALLED_APPS = [
    'update_till.apps.UpdateTillConfig',
    'manage_orders.apps.ManageOrdersConfig',
    'cashup.apps.CashupConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'epos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'epos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/staticfiles/'
# Use a dedicated directory for collected static files (after running collectstatic)
STATIC_ROOT = BASE_DIR / 'collected_static'
# Source directories for static assets during development
STATICFILES_DIRS = [
    BASE_DIR / 'staticfiles',  # contains bootstrap-5.3.7-dist etc.
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# When behind a proxy/SSL terminator (e.g., PythonAnywhere), tell Django to trust X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Auth redirects
# Redirect unauthenticated users to the crew login and, after login, to Cash-up
LOGIN_URL = '/cashup/crew-login/'
LOGIN_REDIRECT_URL = '/cashup/'
LOGOUT_REDIRECT_URL = '/cashup/crew-login/'
