# Generated by Django 5.2.4 on 2025-08-12 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_band', models.IntegerField()),
                ('vat_basis', models.CharField(choices=[('take', 'Takeaway'), ('eat', 'Eatin')], max_length=4)),
                ('show_net', models.BooleanField(default=False)),
                ('total_gross', models.IntegerField(default=0, help_text='Total in pence (gross)')),
                ('total_net', models.IntegerField(default=0, help_text='Total in pence (net, takeaway basis)')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.IntegerField()),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('combo', 'Combo')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('variant_label', models.CharField(blank=True, max_length=40)),
                ('is_meal', models.BooleanField(default=False)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price_gross', models.IntegerField(help_text='Pence')),
                ('line_total_gross', models.IntegerField(help_text='Pence')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manage_orders.order')),
            ],
        ),
    ]
