# Generated by Django 5.2.4 on 2025-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0002_order_completed_at_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='crew_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
