# Generated by Django 5.2.4 on 2025-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0003_order_crew_id_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('packed', 'Packed'), ('dispatched', 'Dispatched')], default='preparing', max_length=12),
        ),
    ]
