# Generated by Django 5.2.4 on 2025-10-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0006_channel_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
