# Generated by Django 5.2.4 on 2025-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0007_alter_channelmapping_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmapping',
            name='is_third_party_delivery',
            field=models.BooleanField(default=False, help_text='True if this channel is a third‑party delivery platform (e.g., Just Eat, Deliveroo, Uber)'),
        ),
    ]
