# Generated by Django 5.2.4 on 2025-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0008_channelmapping_is_third_party_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmapping',
            name='is_third_party_delivery',
            field=models.BooleanField(default=False, help_text='True if this channel is a third‑party delivery platform (e.g., Just Eat - Deliver, Deliveroo - Deliver, Uber - Deliver)'),
        ),
    ]
