# Generated by Django 5.2.4 on 2025-11-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0009_alter_channelmapping_is_third_party_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelMapping',
        ),
    ]
