# Generated by Django 5.2.4 on 2025-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0010_delete_channelmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='band_co_number',
            field=models.CharField(blank=True, default='', help_text='Channel/supplier name associated with the selected price band (PriceBand.SUPPLIER_NAME).', max_length=30),
        ),
    ]
