# Generated by Django 5.2.4 on 2025-12-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0013_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='split_voucher_pence',
            field=models.IntegerField(default=0),
        ),
    ]
