# Generated by Django 5.2.4 on 2025-10-21 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=2, help_text='Expected cash amount based on transactions', max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, help_text='Actual cash amount counted at the end of the shift', max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, help_text='Difference between expected and actual amounts', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the denomination (e.g., 'Five Pound Note')", max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Monetary value of the denomination (e.g., 5.00)', max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CashUpEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, help_text='Number of this denomination counted')),
                ('cashup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cashup.cashup')),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashup.denomination')),
            ],
            options={
                'ordering': ['denomination__value'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Float',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total float amount at the start of the shift', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='float', to='cashup.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cashup',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashup', to='cashup.shift'),
        ),
    ]
